ALL_VALID: no

DESCRIPTION_KEYWORDS:
- escalation
- privesc
- elevated privilege
- escalation of privilege
- " sudo "
- " suid "
- " pe "
- " UAC "
- User Account Control
- linpeas
- winpeas
- docker
- kubernetes
- podman
- " CBS "

DESCRIPTION_KEYWORDS_I:
- escalation

PRODUCT_KEYWORDS:
- sudo
- docker
- kubernetes
- gafana
- mikrotik
- zapier
- okta
- jamf
- podman
- container
- linux
- windows
- macos

PRODUCT_KEYWORDS_I:
- linux
- windows
- macos
- zapier
- okta
- jamf
